#Workflow to show how to develop workflows in branches
name: Develop in a branch
on: [pull_request, workflow_dispatch]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "workflow triggered in branch '${{ github.ref }}'."
                echo "workflow triggered by event '${{ github.event_name }}'."
                echo "workflow triggered by actor '${{ github.actor }}'."
    job2:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4.1.0
            - uses: devops-actions/actionlint@v0.1.2
            - run: echo "PR title is '${{ github.event.pull_request.title }}'."
            