# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - main
      - 'release/**'
    # paths:
    #   - 'src/**'
  # Allow the user to manually trigger that workflow
  workflow_dispatch:
  # schedule:
    # Runs every hour from 9am to 5pm
    # - cron: '0 9-17 * * *'
jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
          echo "Hello ${{vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "My secret is 👍 '${{ secrets.MY_SECRET }}'."
          echo "Current branch is '${{ github.ref }}'."
        shell: bash
      - name: checkout
        uses: actions/checkout@v4.1.0
      - name: List files in repository
        run: tree
  Test:
    runs-on: ubuntu-latest
    environment: tst
    needs: first_job
    steps:
    - run: |
        echo "Hello ${{ vars.MY_ENV_VAR }} from ${{ github.actor }}."
        sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
        echo "My secret is '$sec'."
  Load-Test:
    runs-on: ubuntu-latest
    environment: dev
    needs: first_job
    steps:
    - run: |
        echo "Hello ${{ vars.MY_ENV_VAR }} from ${{ github.actor }}."
        sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
        echo "My secret is '$sec'."
  Production:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://writeabout.net
    needs: [Test, Load-Test]
    steps:
    - run: |
        echo "Hello ${{ vars.MY_ENV_VAR }} from ${{ github.actor }}."
        sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
        echo "My secret is '$sec'."
